### ISSUE TITLE
no data transfer indicator

### ISSUE THREAD

**Issue by makar0nin** [PixelExperience-Devices/device_xiaomi_santoni#2]
There are no signs on the indicators of the WIFI and mobile network with active data transfer (there used to be arrows)
![photo_2019-06-04_15-26-23](https://user-images.githubusercontent.com/38000742/58879125-952a9100-86dd-11e9-8e11-cfbae181874c.jpg)

**Comment by nobodyknowsmyname** [comment]
Check System > Statusbar
