### ISSUE TITLE
Fixing Goodix fingerprint scanner

### ISSUE THREAD

**Issue by martin-lukas** [PixelExperience-Devices/device_xiaomi_santoni#6]
Hi, Is there a plan to fix the Goodix fingerprint scanners? I just installed this ROM and mine doesn't work, so I guess mine is Goodix. Sorry if this is not the right place for this.

**Comment by nobodyknowsmyname** [comment]
Hey. If you do not know, I have long ceased to support Santoni. And if you are talking about Android 10 - then there is no fix yet, unfortunately

**Comment by martin-lukas** [comment]
Oh, sorry... I didn't know. Thanks anyway for letting me know.
