### ISSUE TITLE
aosp.dependencies link broken

### ISSUE THREAD

**Issue by fanrenng** [PixelExperience-Devices/device_xiaomi_santoni#8]
- https://github.com/pranaya2005/proprietary_vendor_xiaomi
- https://github.com/pranaya2005/android_kernel_xiaomi_santoni

are removed

**Comment by smarek** [comment]
@fanrenng did you found suitable mirrors?

@pranaya2005 could you please hint a replacements? seems like you deleted the repositories, thank you

**Comment by pranayadmn** [comment]
> @fanrenng did you found suitable mirrors?
> 
> @pranaya2005 could you please hint a replacements? seems like you deleted the repositories, thank you

These device sources were for Android 10 and also weren't even ready for kernel 4.9. Most of the developers abandoned this device (including myself) and only a handful of them are working on it now. I suggest you to use the device sources from [here](https://github.com/Jabiyeff-Project) or [here](https://github.com/ProtoDump) and adapt them for PixelExperience.

**Comment by smarek** [comment]
@pranaya2005 thank you, i'd be happy just with fresh build of Android 10, but since i have full development locally, i can try to adapt Jabiyeff-Project for PixelExperience, i suppose i should port the Jabiyeff-Project/device-santoni on to PixelExperience-Devices/device_xiaomi_msm8937-common template?

**Comment by pranayadmn** [comment]
> @pranaya2005 thank you, i'd be happy just with fresh build of Android 10, but since i have full development locally, i can try to adapt Jabiyeff-Project for PixelExperience, i suppose i should port the Jabiyeff-Project/device-santoni on to PixelExperience-Devices/device_xiaomi_msm8937-common template?

I guess we should continue this discussion somewhere else, if you're on Telegram please ping me here: [@pranaya2005](https://t.me/pranaya2005). Also, @fanrenng if possible please close this issue here since I'm no longer associated with the PixelExperience Project.

**Comment by fanrenng** [comment]
OK, thank you
I will close it
